## notebook setup and configuration

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import petsc4py
from petsc4py import PETSc

# initialization of `Vec`  sequential vectors

In [2]:
# vector size
n = 10

## generic vector creation

Here, we create a generic vector and set its attributes. In order to make the vector usable, we call the `assemblyBegin(), assemblyEnd()` methods.

In [3]:
# creates a standard, sequential array-style vector.
x = PETSc.Vec().create()
x.setSizes(n)
x.setType('seq')

In [4]:
# make the vector usable
x.assemblyBegin()
x.assemblyEnd()

The vector is filled with zeros by default.

In [5]:
x.getArray()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## constructing sequential vectors with `createSeq()`

We can call the convenience function `createSeq` to create the same sequential vector  

In [6]:
# does the same as in the 'generic' creation above
x = PETSc.Vec().createSeq(n)

In [7]:
x.getArray()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# setting values

### setting a constant vector

In [8]:
x.set(1)
x.getArray()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### `setValue` for setting single values

In [9]:
x.setValue(0, 0)
x.getArray()

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### `setValues` for setting multiple values

In [10]:
x.setValues(range(n), [2**n for n in range(n)])
x.getArray()

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

### zero-ing a vector

In [11]:
# puts a 0.0 in each element of a vector
x.zeroEntries()
x.getArray()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# vector information

### type, dimension, values

In [12]:
# vector type
x.Type()

In [13]:
# Returns the global number of elements of the vector.
x.getSize()

10

In [14]:
# Gets values from certain locations of a vector. 
# Currently can only get values on the same processor
x.getValues(indices=[0, 1, n-1])

array([0., 0., 0.])

### `max` and `min`

In [23]:
# Determines the maximum vector component and its location.
x.setValues(range(n), range(n))
x.max()

(9, 9.0)

In [25]:
# Determines the minimum vector component and its location.
x.min()

(0, 0.0)

### vector norms

In [27]:
x.getArray()

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
# Computes the vector norm.
print('L1 norm: {}'.format(x.norm(PETSc.NormType.NORM_1)))
print('L2 norm: {}'.format(x.norm(PETSc.NormType.NORM_2)))
print('L_infty norm: {}'.format(x.norm(PETSc.NormType.NORM_INFINITY)))

L1 norm: 45.0
L2 norm: 16.881943016134134
L_infty norm: 9.0


In [34]:
# defaults to L2 norm
x.norm()

16.881943016134134

# vector operations

## arithmetic operations

### sum

In [15]:
# Computes the sum of all the components of a vector.
x.set(1)
x.sum()

10.0

### dot product

In [16]:
# dot product with itself
x.dot(x)

10.0

## in-place operations

### logarithm

In [17]:
# Replaces each component of a vector by log(x_i), the natural logarithm
x.setValues(range(n), range(n))
x.log()
x.getArray()

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])