## notebook setup and configuration

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import petsc4py
from petsc4py import PETSc

# initialization of `Vec`  sequential vectors

In [2]:
# vector size
n = 10

## generic vector creation

Here, we create a generic vector and set its attributes. In order to make the vector usable, we call the `assemblyBegin(), assemblyEnd()` methods.

In [3]:
# creates a standard, sequential array-style vector.
x = PETSc.Vec().create()
x.setSizes(n)
x.setType('seq')

In [4]:
# make the vector usable
x.assemblyBegin()
x.assemblyEnd()

The vector is filled with zeros by default.

In [5]:
x.getArray()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## constructing sequential vectors with `createSeq()`

We can call the convenience function `createSeq` to create the same sequential vector  

In [6]:
# does the same as in the 'generic' creation above
x = PETSc.Vec().createSeq(n)

In [7]:
x.getArray()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# setting values

### setting a constant vector

In [8]:
x.set(1)
x.getArray()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### `setValue` for setting single values

In [9]:
x.setValue(0, 0)
x.getArray()

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### `setValues` for setting multiple values

In [10]:
x.setValues(range(n), [2**n for n in range(n)])
x.getArray()

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

### zero-ing a vector

In [11]:
# puts a 0.0 in each element of a vector
x.zeroEntries()
x.getArray()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# vector information

### type, dimension, values

In [12]:
# vector type
x.Type()

In [13]:
# Returns the global number of elements of the vector.
x.getSize()

10

In [14]:
# Gets values from certain locations of a vector. 
# Currently can only get values on the same processor
x.getValues(indices=[0, 1, n-1])

array([0., 0., 0.])

### `max` and `min`

In [15]:
# Determines the maximum vector component and its location.
x.setValues(range(n), range(n))
x.max()

(9, 9.0)

In [16]:
# Determines the minimum vector component and its location.
x.min()

(0, 0.0)

### vector norms

In [17]:
x.getArray()

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
# Computes the vector norm.
print('L1 norm: {}'.format(x.norm(PETSc.NormType.NORM_1)))
print('L2 norm: {}'.format(x.norm(PETSc.NormType.NORM_2)))
print('L_infty norm: {}'.format(x.norm(PETSc.NormType.NORM_INFINITY)))

L1 norm: 45.0
L2 norm: 16.881943016134134
L_infty norm: 9.0


In [19]:
# defaults to L2 norm
x.norm()

16.881943016134134

# vector operations

## arithmetic operations

### sum

In [20]:
# Computes the sum of all the components of a vector.
x.set(1)
x.sum()

10.0

### dot product

In [21]:
# dot product with itself
x.dot(x)

10.0

## in-place operations

### multiply by a scalar

In [22]:
x.setValues(range(n), range(n))
print(x.getArray())
x.scale(4.0)
x.getArray()

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.])

### shift / add / subtract

In [23]:
# Shifts all of the components of a vector by computing x[i] = x[i] + shift.
x.shift(1)
x.getArray()

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37.])

### reciprocal

In [24]:
# Replaces each component of a vector by its reciprocal.
# Note that reciprocal of 0 is 0
x.setValues(range(n), range(n))
x.reciprocal()
x.getArray()

array([0.        , 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### logarithm

In [25]:
# Replaces each component of a vector by log(x_i), the natural logarithm
# note that log(0) returns -inf
x.setValues(range(n), range(n))
x.log()
x.getArray()

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### set to random values

In [29]:
# Sets all components of a vector to random numbers.
x.set(1)
x.setRandom()
x.getArray()

array([0.72003197, 0.06179397, 0.01002234, 0.14463932, 0.39777781,
       0.07303659, 0.10386629, 0.25078039, 0.98405227, 0.73851607])

### normalize

In [38]:
# Normalizes a vector by 2-norm.
x.set(1)
print('x:\n{}\n'.format(x.getArray()))

x.normalize()
print('x.normalize():\n{}\n'.format(x.getArray()))
print('L2 norm of x:\n{}\n'.format(x.norm()))

x:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

x.normalize():
[0.31622777 0.31622777 0.31622777 0.31622777 0.31622777 0.31622777
 0.31622777 0.31622777 0.31622777 0.31622777]

L2 norm of x:
1.0



In [32]:
x.norm()

1.0